/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.company.views;

import com.company.models.ConexionPacVac;
import com.company.models.ConexionVacunasDisponibles;
import com.company.models.ConexionVacunasUsadas;
import java.awt.Color;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author HP
 */
public class ConfirmarVacuna extends javax.swing.JPanel {

    /**
     * Creates new form Inicio_PersonalSalud
     */
    public ConfirmarVacuna() {
        initComponents();
        initStyle();
//        ConexionPacVac objetoPacVac=new ConexionPacVac();
//        objetoPacVac.mostrarPacVac(tbHistorialMedico);
    }
    public ConfirmarVacuna(ConexionPacVac pacienteVacunado) {
        initComponents();
        initStyle();
        DateTimeFormatter formatter=DateTimeFormatter.ofPattern("dd/MM/yyyy");
        LocalDate fechaActual=LocalDate.now();
        txtDni.setText(pacienteVacunado.getDniPacVac());
        txtNombre.setText(pacienteVacunado.getNombrePacVac());
        txtApellido.setText(pacienteVacunado.getApellidoVacPac());
        txtDireccion.setText(pacienteVacunado.getDirecVacPac());
        txtCelular.setText(pacienteVacunado.getCelVacPac());
        txtFechaNac.setText(pacienteVacunado.getFechaNacPacVac());
        txtKit.setText(pacienteVacunado.getKitVacPac());
        txtLote.setText(pacienteVacunado.getLotePacVac());
        txtEnfermedad.setText(pacienteVacunado.getEnferVacPac());
        txtDosis.setText(pacienteVacunado.getDosisVacPac());
        txtFechaVac.setText(fechaActual.format(formatter));
    }
    private void initStyle(){
        lblBienvenido.putClientProperty( "FlatLaf.style", "font: bold $h3.regular.font" );
        lblBienvenido.setForeground(Color.BLACK);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jSeparator4 = new javax.swing.JSeparator();
        lblBienvenido = new javax.swing.JLabel();
        txtDni = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtCelular = new javax.swing.JTextField();
        txtFechaNac = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        txtLote = new javax.swing.JTextField();
        txtKit = new javax.swing.JTextField();
        txtEnfermedad = new javax.swing.JTextField();
        txtDosis = new javax.swing.JTextField();
        txtFechaVac = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        jSeparator13 = new javax.swing.JSeparator();
        jSeparator14 = new javax.swing.JSeparator();
        btnConfirmar = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1060, 524));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        bg.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 320, 20));

        lblBienvenido.setText("Bien, llegados aqui se nescesita confirmar si todos los datos ingresados en las partes anteriores son los correctos para poder registrarlos.");
        bg.add(lblBienvenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1040, 32));

        txtDni.setEditable(false);
        txtDni.setBorder(null);
        txtDni.setFocusable(false);
        txtDni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDniActionPerformed(evt);
            }
        });
        bg.add(txtDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 320, 20));

        txtNombre.setEditable(false);
        txtNombre.setBorder(null);
        txtNombre.setFocusable(false);
        bg.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 320, 20));

        txtApellido.setEditable(false);
        txtApellido.setBorder(null);
        txtApellido.setFocusable(false);
        bg.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 320, 20));

        txtDireccion.setEditable(false);
        txtDireccion.setBorder(null);
        txtDireccion.setFocusable(false);
        txtDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDireccionActionPerformed(evt);
            }
        });
        bg.add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 320, 20));

        txtCelular.setEditable(false);
        txtCelular.setBorder(null);
        txtCelular.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtCelular.setFocusable(false);
        txtCelular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCelularActionPerformed(evt);
            }
        });
        bg.add(txtCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 320, 20));

        txtFechaNac.setEditable(false);
        txtFechaNac.setBorder(null);
        txtFechaNac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaNacActionPerformed(evt);
            }
        });
        bg.add(txtFechaNac, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 320, 20));

        jLabel2.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        jLabel2.setText("Nacimiento:");
        bg.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

        jLabel3.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        jLabel3.setText("Dosis:");
        bg.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 210, -1, -1));

        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        bg.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 320, 20));

        jLabel4.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        jLabel4.setText("Apellido:");
        bg.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));
        bg.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 320, 20));

        jLabel5.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        jLabel5.setText("Nombre:");
        bg.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jSeparator7.setForeground(new java.awt.Color(0, 0, 0));
        bg.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 320, 20));

        jLabel6.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        jLabel6.setText("Celular:");
        bg.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        jSeparator8.setForeground(new java.awt.Color(0, 0, 0));
        bg.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 320, 20));

        jLabel7.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        jLabel7.setText("Direccion:");
        bg.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        jSeparator9.setForeground(new java.awt.Color(0, 0, 0));
        bg.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 70, 320, 20));

        txtLote.setEditable(false);
        txtLote.setBorder(null);
        txtLote.setFocusable(false);
        txtLote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLoteActionPerformed(evt);
            }
        });
        bg.add(txtLote, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 90, 320, 20));

        txtKit.setEditable(false);
        txtKit.setBorder(null);
        txtKit.setFocusable(false);
        bg.add(txtKit, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 50, 320, 20));

        txtEnfermedad.setEditable(false);
        txtEnfermedad.setBorder(null);
        txtEnfermedad.setFocusable(false);
        bg.add(txtEnfermedad, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 170, 320, 20));

        txtDosis.setEditable(false);
        txtDosis.setBorder(null);
        txtDosis.setFocusable(false);
        txtDosis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDosisActionPerformed(evt);
            }
        });
        bg.add(txtDosis, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 210, 320, 20));

        txtFechaVac.setEditable(false);
        txtFechaVac.setBorder(null);
        txtFechaVac.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtFechaVac.setFocusable(false);
        txtFechaVac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaVacActionPerformed(evt);
            }
        });
        bg.add(txtFechaVac, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 130, 320, 20));

        jLabel8.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        jLabel8.setText("DNI:");
        bg.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jLabel9.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        jLabel9.setText("Kit:");
        bg.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 50, -1, -1));

        jLabel10.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        jLabel10.setText("Lote:");
        bg.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 90, -1, -1));

        jLabel11.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        jLabel11.setText("Fecha:");
        bg.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 130, -1, -1));

        jLabel12.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        jLabel12.setText("Enfermedad:");
        bg.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 170, -1, -1));

        jSeparator10.setForeground(new java.awt.Color(0, 0, 0));
        bg.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 320, 20));

        jSeparator11.setForeground(new java.awt.Color(0, 0, 0));
        bg.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 230, 320, 20));

        jSeparator12.setForeground(new java.awt.Color(0, 0, 0));
        bg.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 190, 320, 20));

        jSeparator13.setForeground(new java.awt.Color(0, 0, 0));
        bg.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 150, 320, 20));

        jSeparator14.setForeground(new java.awt.Color(0, 0, 0));
        bg.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 110, 320, 20));

        btnConfirmar.setBackground(new java.awt.Color(21, 101, 192));
        btnConfirmar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnConfirmar.setForeground(new java.awt.Color(255, 255, 255));
        btnConfirmar.setText("Confirmar");
        btnConfirmar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });
        bg.add(btnConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 260, 188, 43));

        add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1062, 530));
    }// </editor-fold>//GEN-END:initComponents

    private void txtDniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDniActionPerformed

    private void txtDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDireccionActionPerformed

    private void txtCelularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCelularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCelularActionPerformed

    private void txtFechaNacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaNacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaNacActionPerformed

    private void txtLoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLoteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLoteActionPerformed

    private void txtDosisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDosisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDosisActionPerformed

    private void txtFechaVacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaVacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaVacActionPerformed

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        // TODO add your handling code here:
        ConexionPacVac objetoPacVac=new ConexionPacVac();
        objetoPacVac.vacunarPaciente(txtDni, txtNombre, txtApellido, txtDireccion, txtCelular, txtFechaNac, txtKit, txtLote, txtEnfermedad, txtDosis);
        ConexionVacunasDisponibles objetoVacuna=new ConexionVacunasDisponibles();
        objetoVacuna.eliminarRegistro(txtKit);
        ConexionVacunasUsadas objetoVacUsa=new ConexionVacunasUsadas();
        objetoVacUsa.registrarVacUsada(txtKit, txtLote, txtEnfermedad, txtDosis);
    }//GEN-LAST:event_btnConfirmarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel lblBienvenido;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtDni;
    private javax.swing.JTextField txtDosis;
    private javax.swing.JTextField txtEnfermedad;
    private javax.swing.JTextField txtFechaNac;
    private javax.swing.JTextField txtFechaVac;
    private javax.swing.JTextField txtKit;
    private javax.swing.JTextField txtLote;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
