/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.company.views;

import com.company.forms.FormVacunarPaciente;
import com.company.models.ConexionPacVac;
import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author HP
 */
public class HistorialPaciente extends javax.swing.JPanel {

    /**
     * Creates new form Inicio_PersonalSalud
     */
    public HistorialPaciente() {
        initComponents();
        initStyle();
        ConexionPacVac objetoPacVac=new ConexionPacVac();
        objetoPacVac.mostrarPacVac(tbHistorialMedico);
    }
    private void initStyle(){
        lblBienvenido.putClientProperty( "FlatLaf.style", "font: bold $h3.regular.font" );
        lblBienvenido.setForeground(Color.BLACK);
        txtBuscarDni.setForeground(new Color(90, 90, 90));
    }
    public ConexionPacVac enviarDatosPaciente(){
        ConexionPacVac pacienteAVacunado=new ConexionPacVac(txtDni.getText(),txtNombre.getText(),
                    txtApellido.getText(),txtDireccion.getText(),txtCelular.getText(),
                    txtFechaNac.getText());
        return pacienteAVacunado;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jSeparator4 = new javax.swing.JSeparator();
        txtBuscarDni = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbHistorialMedico = new javax.swing.JTable();
        btnBuscarDNI = new javax.swing.JButton();
        lblBienvenido = new javax.swing.JLabel();
        btnNuevoPaciente = new javax.swing.JButton();
        btnSeleccionarPaciente = new javax.swing.JButton();
        txtDni = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtCelular = new javax.swing.JTextField();
        txtFechaNac = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(1060, 524));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        bg.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 830, 20));

        txtBuscarDni.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        txtBuscarDni.setForeground(new java.awt.Color(204, 204, 204));
        txtBuscarDni.setText("Ingrese el DNI del paciente");
        txtBuscarDni.setBorder(null);
        txtBuscarDni.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtBuscarDniMousePressed(evt);
            }
        });
        txtBuscarDni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarDniActionPerformed(evt);
            }
        });
        txtBuscarDni.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarDniKeyReleased(evt);
            }
        });
        bg.add(txtBuscarDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 839, 43));

        tbHistorialMedico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbHistorialMedico.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tbHistorialMedico.setEditingColumn(0);
        tbHistorialMedico.setEditingRow(0);
        tbHistorialMedico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbHistorialMedicoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbHistorialMedico);

        bg.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 111, 1050, 230));

        btnBuscarDNI.setBackground(new java.awt.Color(21, 101, 192));
        btnBuscarDNI.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBuscarDNI.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarDNI.setText("Buscar por DNI");
        btnBuscarDNI.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnBuscarDNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarDNIActionPerformed(evt);
            }
        });
        bg.add(btnBuscarDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 50, 191, 43));

        lblBienvenido.setText("Bienvenido, en este apartado puede buscar las vacunas del paciente usando su DNI o registrar uno nuevo de ser nescesario.");
        bg.add(lblBienvenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1040, 32));

        btnNuevoPaciente.setBackground(new java.awt.Color(21, 101, 192));
        btnNuevoPaciente.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnNuevoPaciente.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevoPaciente.setText("Nuevo paciente");
        btnNuevoPaciente.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnNuevoPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoPacienteActionPerformed(evt);
            }
        });
        bg.add(btnNuevoPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 350, 188, 43));

        btnSeleccionarPaciente.setBackground(new java.awt.Color(21, 101, 192));
        btnSeleccionarPaciente.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSeleccionarPaciente.setForeground(new java.awt.Color(255, 255, 255));
        btnSeleccionarPaciente.setText("Seleccionar paciente");
        btnSeleccionarPaciente.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnSeleccionarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarPacienteActionPerformed(evt);
            }
        });
        bg.add(btnSeleccionarPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 188, 43));

        txtDni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDniActionPerformed(evt);
            }
        });
        bg.add(txtDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 500, 128, 20));
        bg.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 500, 128, 20));
        bg.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 500, 128, 20));

        txtDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDireccionActionPerformed(evt);
            }
        });
        bg.add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 490, 128, 30));

        txtCelular.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtCelular.setEnabled(false);
        txtCelular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCelularActionPerformed(evt);
            }
        });
        bg.add(txtCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, 128, 30));

        txtFechaNac.setBorder(null);
        txtFechaNac.setFocusable(false);
        txtFechaNac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaNacActionPerformed(evt);
            }
        });
        bg.add(txtFechaNac, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 490, 200, 20));

        add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1062, 530));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarDNIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarDNIActionPerformed

    private void btnNuevoPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoPacienteActionPerformed
        // TODO add your handling code here:
        FormVacunarPaciente.showJPanel(new NuevoPaciente());
    }//GEN-LAST:event_btnNuevoPacienteActionPerformed

    private void txtBuscarDniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarDniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarDniActionPerformed

    private void txtBuscarDniMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBuscarDniMousePressed
        // TODO add your handling code here:
        if(txtBuscarDni.getText().equals("Ingrese el DNI del paciente")){
            txtBuscarDni.setText("");
            txtBuscarDni.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtBuscarDniMousePressed

    private void btnSeleccionarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarPacienteActionPerformed
        // TODO add your handling code here:
        if(!txtDni.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Se selecciona al paceinte:\n"+
                "DNI: "+txtDni.getText()+
                "\nNombre "+txtNombre.getText()+
                "\nApellido: "+txtApellido.getText()+
                "\nDireccion: "+txtDireccion.getText()+
                "\nCelular: "+txtCelular.getText()+
                "\nFecha de nacimiento: "+txtFechaNac.getText());
            VacunasDIsponibles panelVacuna= new VacunasDIsponibles(enviarDatosPaciente());
            FormVacunarPaciente.showJPanel(panelVacuna);
        }else{
            JOptionPane.showMessageDialog(null, "Seleccione un paciente.");
        }
        
    }//GEN-LAST:event_btnSeleccionarPacienteActionPerformed

    private void txtDniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDniActionPerformed

    private void txtDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDireccionActionPerformed

    private void txtCelularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCelularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCelularActionPerformed

    private void tbHistorialMedicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbHistorialMedicoMouseClicked
        // TODO add your handling code here:
        ConexionPacVac objetoPaciente=new ConexionPacVac();
        objetoPaciente.selecPacVac(tbHistorialMedico, txtDni, txtNombre, txtApellido, txtDireccion, txtCelular, txtFechaNac);
    }//GEN-LAST:event_tbHistorialMedicoMouseClicked

    private void txtFechaNacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaNacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaNacActionPerformed

    private void txtBuscarDniKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarDniKeyReleased
        // TODO add your handling code here:
        ConexionPacVac pacBuscadoDNI=new ConexionPacVac();
        pacBuscadoDNI.filtrarPorDNI(tbHistorialMedico, txtBuscarDni);
    }//GEN-LAST:event_txtBuscarDniKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JButton btnBuscarDNI;
    private javax.swing.JButton btnNuevoPaciente;
    private javax.swing.JButton btnSeleccionarPaciente;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel lblBienvenido;
    private javax.swing.JTable tbHistorialMedico;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtBuscarDni;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtDni;
    private javax.swing.JTextField txtFechaNac;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
