/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.company.views;

import com.company.forms.FormVacunarPaciente;
import com.company.models.ConexionPacVac;
import com.company.models.ConexionRegistrarUsuarioTest;
import com.company.models.ConexionVacunasDisponibles;
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author HP
 */
public class ModificarUsuario extends javax.swing.JPanel {

    /**
     * Creates new form Inicio_PersonalSalud
     */
    public ModificarUsuario() {
        initComponents();
        initStyle();
//        ConexionPacVac objetoPacVac=new ConexionPacVac();
//        objetoPacVac.mostrarPacVac(tbHistorialMedico);
    }
    public ModificarUsuario(ConexionRegistrarUsuarioTest modUsuario){
        initComponents();
        initStyle();
        txtDNI.setText(modUsuario.getDni());
        txtNombre.setText(modUsuario.getNombre());
        txtApellido.setText(modUsuario.getApellido());
        txtUsuario.setText(modUsuario.getUsuario());
        txtContraseña.setText(modUsuario.getClave());
        cbRol.setSelectedItem(modUsuario.getRol());
    }

    private void initStyle() {
        lblBienvenido.putClientProperty("FlatLaf.style", "font: bold $h3.regular.font");
        lblBienvenido.setForeground(Color.BLACK);
        txtDNI.setForeground(new Color(90,90,90));
        txtNombre.setForeground(new Color(90,90,90));
        txtApellido.setForeground(new Color(90,90,90));
//        txtDosis.setForeground(new Color(90,90,90));
        txtUsuario.setForeground(new Color(90,90,90));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        lblBienvenido = new javax.swing.JLabel();
        txtDNI = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtUsuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        btnModificar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        txtContraseña = new javax.swing.JTextField();
        jSeparator11 = new javax.swing.JSeparator();
        cbRol = new javax.swing.JComboBox<>();

        setPreferredSize(new java.awt.Dimension(1060, 524));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBienvenido.setText("Modifique los datos de la vacuna.");
        bg.add(lblBienvenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1040, 32));

        txtDNI.setEditable(false);
        txtDNI.setBorder(null);
        txtDNI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtDNIMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtDNIMousePressed(evt);
            }
        });
        txtDNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDNIActionPerformed(evt);
            }
        });
        bg.add(txtDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 410, 20));

        txtNombre.setBorder(null);
        txtNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtNombreMousePressed(evt);
            }
        });
        bg.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 410, 20));

        txtApellido.setBorder(null);
        txtApellido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtApellidoMousePressed(evt);
            }
        });
        bg.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 410, 20));

        txtUsuario.setBorder(null);
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        bg.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 410, 20));

        jLabel2.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        jLabel2.setText("Contraseña:");
        bg.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        bg.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 410, 20));

        jLabel4.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        jLabel4.setText("Apellido:");
        bg.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));
        bg.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 410, 20));

        jLabel5.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        jLabel5.setText("Nombre:");
        bg.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jSeparator7.setForeground(new java.awt.Color(0, 0, 0));
        bg.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 410, 20));

        jSeparator8.setForeground(new java.awt.Color(0, 0, 0));
        bg.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 410, 20));

        jLabel7.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        jLabel7.setText("Rol:");
        bg.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        jLabel8.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        jLabel8.setText("DNI:");
        bg.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jSeparator10.setForeground(new java.awt.Color(0, 0, 0));
        bg.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 410, 20));

        btnModificar.setBackground(new java.awt.Color(21, 101, 192));
        btnModificar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnModificar.setForeground(new java.awt.Color(255, 255, 255));
        btnModificar.setText("Modificar");
        btnModificar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        bg.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 210, 43));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ModificarUsuaroImagen.png"))); // NOI18N
        bg.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 46, 530, 360));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        bg.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 50, 10, 330));

        jLabel3.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        jLabel3.setText("Usuario:");
        bg.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        txtContraseña.setBorder(null);
        txtContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContraseñaActionPerformed(evt);
            }
        });
        bg.add(txtContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 410, 20));

        jSeparator11.setForeground(new java.awt.Color(0, 0, 0));
        bg.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 410, 20));

        cbRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Admin", "Inventarista", "Personal medico" }));
        cbRol.setBorder(null);
        cbRol.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbRolMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cbRolMousePressed(evt);
            }
        });
        cbRol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbRolActionPerformed(evt);
            }
        });
        bg.add(cbRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 410, -1));

        add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1062, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txtDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDNIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDNIActionPerformed

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        ConexionRegistrarUsuarioTest usuarioModificar=new ConexionRegistrarUsuarioTest();
        usuarioModificar.modificarRegistro(txtDNI, txtNombre, txtApellido, cbRol, txtApellido, txtUsuario);
    }//GEN-LAST:event_btnModificarActionPerformed

    private void txtDNIMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDNIMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDNIMouseClicked

    private void txtDNIMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDNIMousePressed
        // TODO add your handling code here:
//        if (txtKit.getText().equals("Digiete el DNI del paciente")) {
//            txtKit.setText("");
//            txtKit.setForeground(Color.BLACK);
//        }
//        if (txtLote.getText().isEmpty() || txtEnfermedad.getText().isEmpty() || txtDosis.getText().isEmpty()) {
//            txtLote.setText("Digite el nombre(s) del paciente");
//            txtLote.setForeground(new Color(90, 90, 90));
//            txtEnfermedad.setText("Digite los apellidos del paciente");
//            txtEnfermedad.setForeground(new Color(90, 90, 90));
//            txtDosis.setText("Digite la direccion del paciente");
//            txtDosis.setForeground(new Color(90, 90, 90));
//        }
    }//GEN-LAST:event_txtDNIMousePressed

    private void txtNombreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreMousePressed
        // TODO add your handling code here:
//        if (txtLote.getText().equals("Digite el nombre(s) del paciente")) {
//            txtLote.setText("");
//            txtLote.setForeground(Color.BLACK);
//        }
//        if (txtKit.getText().isEmpty() || txtEnfermedad.getText().isEmpty() || txtDosis.getText().isEmpty()) {
//            txtKit.setText("Digiete el DNI del paciente");
//            txtKit.setForeground(new Color(90, 90, 90));
//            txtEnfermedad.setText("Digite los apellidos del paciente");
//            txtEnfermedad.setForeground(new Color(90, 90, 90));
//            txtDosis.setText("Digite la direccion del paciente");
//            txtDosis.setForeground(new Color(90, 90, 90));
//        }
    }//GEN-LAST:event_txtNombreMousePressed

    private void txtApellidoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtApellidoMousePressed
        // TODO add your handling code here:
//        if (txtEnfermedad.getText().equals("Digite los apellidos del paciente")) {
//            txtEnfermedad.setText("");
//            txtEnfermedad.setForeground(Color.BLACK);
//        }
//        if (txtKit.getText().isEmpty() || txtLote.getText().isEmpty() || txtDosis.getText().isEmpty()) {
//            txtKit.setText("Digiete el DNI del paciente");
//            txtKit.setForeground(new Color(90, 90, 90));
//            txtLote.setText("Digite el nombre(s) del paciente");
//            txtLote.setForeground(new Color(90, 90, 90));
//            txtDosis.setText("Digite la direccion del paciente");
//            txtDosis.setForeground(new Color(90, 90, 90));
//        }
    }//GEN-LAST:event_txtApellidoMousePressed

    private void txtContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContraseñaActionPerformed

    private void cbRolMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbRolMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cbRolMouseClicked

    private void cbRolMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbRolMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbRolMousePressed

    private void cbRolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbRolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbRolActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JButton btnModificar;
    private javax.swing.JComboBox<String> cbRol;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JLabel lblBienvenido;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtContraseña;
    private javax.swing.JTextField txtDNI;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
