/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.company.views;

import com.company.forms.FormRegistrarNueboUsuarioTest;
import com.company.forms.FormRegistrarNuevosUsuarios;
import com.company.forms.FormRegistrarVacunas;
import com.company.forms.FormVacunarPaciente;
import com.company.models.ConexionPacVac;
import com.company.models.ConexionRegistrarUsuarioTest;
import com.company.models.ConexionUsuario;
import com.company.models.ConexionVacunasDisponibles;
import java.awt.Color;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author HP
 */
public class UsuariosDIsponibles extends javax.swing.JPanel {

    /**
     * Creates new form Inicio_PersonalSalud
     */
    public UsuariosDIsponibles() {
        initComponents();
        initStyle();
        ConexionRegistrarUsuarioTest objetoRegUsu=new ConexionRegistrarUsuarioTest();
        objetoRegUsu.mostrarUsuarios(tbTotalUsuarios);
    }

    private void initStyle(){
        lblBienvenido.putClientProperty( "FlatLaf.style", "font: bold $h3.regular.font" );
        lblBienvenido.setForeground(Color.BLACK);
        txtDNIBuscar.setForeground(new Color(90,90,90));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jSeparator4 = new javax.swing.JSeparator();
        txtDNIBuscar = new javax.swing.JTextField();
        lblBienvenido = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbTotalUsuarios = new javax.swing.JTable();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtDni = new javax.swing.JTextField();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnBuscarDNI = new javax.swing.JButton();
        cboRol = new javax.swing.JComboBox<>();
        txtClave = new javax.swing.JTextField();
        txtUsuario = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(1060, 524));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        bg.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 830, 10));

        txtDNIBuscar.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        txtDNIBuscar.setForeground(new java.awt.Color(204, 204, 204));
        txtDNIBuscar.setText("Ingrese el DNI que se buscara");
        txtDNIBuscar.setBorder(null);
        txtDNIBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtDNIBuscarMousePressed(evt);
            }
        });
        txtDNIBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDNIBuscarActionPerformed(evt);
            }
        });
        txtDNIBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDNIBuscarKeyReleased(evt);
            }
        });
        bg.add(txtDNIBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 839, 43));

        lblBienvenido.setText("Bienvenido, en este apartado puede buscar los usuarios disponibles para usando su DNI.");
        bg.add(lblBienvenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1040, 32));

        tbTotalUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbTotalUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tbTotalUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbTotalUsuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbTotalUsuarios);

        bg.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 111, 1050, 230));
        bg.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 500, 130, 20));
        bg.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 490, 110, 20));

        txtDni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDniActionPerformed(evt);
            }
        });
        bg.add(txtDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 490, 80, 20));

        btnModificar.setBackground(new java.awt.Color(21, 101, 192));
        btnModificar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnModificar.setForeground(new java.awt.Color(255, 255, 255));
        btnModificar.setText("Modificar");
        btnModificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        bg.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 188, 43));

        btnEliminar.setBackground(new java.awt.Color(21, 101, 192));
        btnEliminar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("Eliminar");
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        bg.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 350, 188, 43));

        btnBuscarDNI.setBackground(new java.awt.Color(21, 101, 192));
        btnBuscarDNI.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBuscarDNI.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarDNI.setText("Buscar por DNI");
        btnBuscarDNI.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscarDNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarDNIActionPerformed(evt);
            }
        });
        bg.add(btnBuscarDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 50, 191, 43));

        cboRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Admin", "Inventarista", "Personal medico" }));
        bg.add(cboRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 480, -1, -1));

        txtClave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClaveActionPerformed(evt);
            }
        });
        bg.add(txtClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 480, -1, -1));
        bg.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 480, -1, -1));

        add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1062, 530));
    }// </editor-fold>//GEN-END:initComponents

    private void txtDNIBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDNIBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDNIBuscarActionPerformed

    private void txtDNIBuscarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDNIBuscarMousePressed
        // TODO add your handling code here:
        if(txtDNIBuscar.getText().equals("Ingrese el DNI que se buscara")){
            txtDNIBuscar.setText("");
            txtDNIBuscar.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtDNIBuscarMousePressed

    private void tbTotalUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbTotalUsuariosMouseClicked
        // TODO add your handling code here:
        ConexionRegistrarUsuarioTest objetoTegUsu=new ConexionRegistrarUsuarioTest();
        objetoTegUsu.seleccionarUsuario(tbTotalUsuarios, txtDni, txtNombre, txtApellido, cboRol, txtUsuario, txtClave);
    }//GEN-LAST:event_tbTotalUsuariosMouseClicked

    private void txtDniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDniActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        if (!txtDni.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Se modifica el usuario:\n"+
                    "\nDNI: "+txtDni.getText()+
                    "\nNombre: "+txtNombre.getText()+
                    "\nApellido: "+txtApellido.getText()+
                    "\nRol: "+cboRol.getSelectedItem().toString()+
                    "\nUsuario: "+txtUsuario.getText()+
                    "\nClave: "+txtClave.getText());
            ConexionRegistrarUsuarioTest modNuevoUser=new ConexionRegistrarUsuarioTest(txtNombre.getText(),
                    txtApellido.getText(), txtDni.getText(), cboRol.getSelectedItem().toString(), 
                    txtUsuario.getText(), txtClave.getText());
            FormRegistrarNuevosUsuarios.showJPanel(new ModificarUsuario(modNuevoUser));
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione uno de los usuarios.");
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        ConexionRegistrarUsuarioTest usuarioEliminar= new ConexionRegistrarUsuarioTest();
        usuarioEliminar.eliminarRegistro(txtDni);
        usuarioEliminar.mostrarUsuarios(tbTotalUsuarios);
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnBuscarDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarDNIActionPerformed
        // TODO add your handling code here:
        ConexionRegistrarUsuarioTest usuarioBuscado=new ConexionRegistrarUsuarioTest();
        usuarioBuscado.filtarPorDNI(tbTotalUsuarios, txtDNIBuscar);
    }//GEN-LAST:event_btnBuscarDNIActionPerformed

    private void txtClaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClaveActionPerformed

    private void txtDNIBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDNIBuscarKeyReleased
        // TODO add your handling code here:
        ConexionRegistrarUsuarioTest usuarioBuscado=new ConexionRegistrarUsuarioTest();
        usuarioBuscado.filtarPorDNI(tbTotalUsuarios, txtDNIBuscar);
    }//GEN-LAST:event_txtDNIBuscarKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JButton btnBuscarDNI;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JComboBox<String> cboRol;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel lblBienvenido;
    private javax.swing.JTable tbTotalUsuarios;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtClave;
    private javax.swing.JTextField txtDNIBuscar;
    private javax.swing.JTextField txtDni;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
