/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.company.views;

import com.company.forms.FormVacunarPaciente;
import com.company.models.ConexionPacVac;
import com.company.models.ConexionVacunasDisponibles;
import java.awt.Color;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author HP
 */
public class VacunasDIsponibles extends javax.swing.JPanel {

    /**
     * Creates new form Inicio_PersonalSalud
     */
    public VacunasDIsponibles() {
        initComponents();
        initStyle();
        ConexionVacunasDisponibles objetoVacDis=new ConexionVacunasDisponibles();
        objetoVacDis.mostrarVacunasDisponibles(tbTotalVacunasDisponibles);
    }
    public VacunasDIsponibles(ConexionPacVac pacienteVacunado){
        initComponents();
        initStyle();
        ConexionVacunasDisponibles objetoVacDis=new ConexionVacunasDisponibles();
        objetoVacDis.mostrarVacunasDisponibles(tbTotalVacunasDisponibles);
        txtDni.setText(pacienteVacunado.getDniPacVac());
        txtNombre.setText(pacienteVacunado.getNombrePacVac());
        txtApellido.setText(pacienteVacunado.getApellidoVacPac());
        txtDireccion.setText(pacienteVacunado.getDirecVacPac());
        txtCelular.setText(pacienteVacunado.getCelVacPac());
        txtFechaNac.setText(pacienteVacunado.getFechaNacPacVac());
    }
    public ConexionPacVac pacienteVacunado (){
        DateTimeFormatter formatter=DateTimeFormatter.ofPattern("dd/MM/yyyy");
        LocalDate fechaActual=LocalDate.now();
        ConexionPacVac pacVac=new ConexionPacVac();
        pacVac.setDniPacVac(txtDni.getText());
        pacVac.setNombrePacVac(txtNombre.getText());
        pacVac.setApellidoVacPac(txtApellido.getText());
        pacVac.setDirecVacPac(txtDireccion.getText());
        pacVac.setCelVacPac(txtCelular.getText());
        pacVac.setFechaNacPacVac(txtFechaNac.getText());
        pacVac.setKitVacPac(txtKit.getText());
        pacVac.setLotePacVac(txtLote.getText());
        pacVac.setEnferVacPac(txtEnfermedad.getText());
        pacVac.setDosisVacPac(txtDosis.getText());
        pacVac.setFechaVac(fechaActual.format(formatter));
        return pacVac;
    }
    private void initStyle(){
        lblBienvenido.putClientProperty( "FlatLaf.style", "font: bold $h3.regular.font" );
        lblBienvenido.setForeground(Color.BLACK);
        txtBuscarKitOLote.setForeground(new Color(90,90,90));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jSeparator4 = new javax.swing.JSeparator();
        txtBuscarKitOLote = new javax.swing.JTextField();
        lblBienvenido = new javax.swing.JLabel();
        btnSeleccionarVacuna = new javax.swing.JButton();
        txtLote = new javax.swing.JTextField();
        txtKit = new javax.swing.JTextField();
        txtEnfermedad = new javax.swing.JTextField();
        txtDosis = new javax.swing.JTextField();
        txtCaduca = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbTotalVacunasDisponibles = new javax.swing.JTable();
        txtNombre = new javax.swing.JTextField();
        txtFechaNac = new javax.swing.JTextField();
        txtCelular = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtDni = new javax.swing.JTextField();
        cbTipoDeBusqueda = new javax.swing.JComboBox<>();

        setPreferredSize(new java.awt.Dimension(1060, 524));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        bg.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 830, 10));

        txtBuscarKitOLote.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        txtBuscarKitOLote.setForeground(new java.awt.Color(204, 204, 204));
        txtBuscarKitOLote.setText("Ingrese el kit o el lote que se buscara");
        txtBuscarKitOLote.setBorder(null);
        txtBuscarKitOLote.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtBuscarKitOLoteMousePressed(evt);
            }
        });
        txtBuscarKitOLote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarKitOLoteActionPerformed(evt);
            }
        });
        txtBuscarKitOLote.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBuscarKitOLoteKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKitOLoteKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBuscarKitOLoteKeyTyped(evt);
            }
        });
        bg.add(txtBuscarKitOLote, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 839, 43));

        lblBienvenido.setText("Bienvenido, en este apartado puede buscar las vacunas disponibles para usar por kit o por lote.");
        bg.add(lblBienvenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1040, 32));

        btnSeleccionarVacuna.setBackground(new java.awt.Color(21, 101, 192));
        btnSeleccionarVacuna.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSeleccionarVacuna.setForeground(new java.awt.Color(255, 255, 255));
        btnSeleccionarVacuna.setText("Seleccionar vacuna");
        btnSeleccionarVacuna.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSeleccionarVacuna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarVacunaActionPerformed(evt);
            }
        });
        bg.add(btnSeleccionarVacuna, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 188, 43));

        txtLote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLoteActionPerformed(evt);
            }
        });
        bg.add(txtLote, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 490, 10, 20));
        bg.add(txtKit, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 490, 90, 20));
        bg.add(txtEnfermedad, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 490, 10, 20));

        txtDosis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDosisActionPerformed(evt);
            }
        });
        bg.add(txtDosis, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 480, 10, 30));

        txtCaduca.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtCaduca.setEnabled(false);
        txtCaduca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCaducaActionPerformed(evt);
            }
        });
        bg.add(txtCaduca, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 480, 10, 30));

        tbTotalVacunasDisponibles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbTotalVacunasDisponibles.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tbTotalVacunasDisponibles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbTotalVacunasDisponiblesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbTotalVacunasDisponibles);

        bg.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 111, 1050, 230));
        bg.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 490, 10, 20));

        txtFechaNac.setForeground(new java.awt.Color(51, 51, 51));
        txtFechaNac.setBorder(null);
        txtFechaNac.setFocusable(false);
        txtFechaNac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaNacActionPerformed(evt);
            }
        });
        bg.add(txtFechaNac, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 490, 200, 20));

        txtCelular.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtCelular.setEnabled(false);
        txtCelular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCelularActionPerformed(evt);
            }
        });
        bg.add(txtCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 490, 10, 30));

        txtDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDireccionActionPerformed(evt);
            }
        });
        bg.add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 480, 10, 30));
        bg.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 490, 10, 20));

        txtDni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDniActionPerformed(evt);
            }
        });
        bg.add(txtDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 490, 80, 20));

        cbTipoDeBusqueda.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cbTipoDeBusqueda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "buscar por kit", "buscar por lote" }));
        cbTipoDeBusqueda.setBorder(null);
        cbTipoDeBusqueda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bg.add(cbTipoDeBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(852, 52, 200, 40));

        add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1062, 530));
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscarKitOLoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarKitOLoteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarKitOLoteActionPerformed

    private void txtBuscarKitOLoteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBuscarKitOLoteMousePressed
        // TODO add your handling code here:
        if(txtBuscarKitOLote.getText().equals("Ingrese el kit o el lote que se buscara")){
            txtBuscarKitOLote.setText("");
            txtBuscarKitOLote.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtBuscarKitOLoteMousePressed

    private void btnSeleccionarVacunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarVacunaActionPerformed
        // TODO add your handling code here:
        if(!txtKit.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Se selecciona la vacuna:\n"+
                "Kit: "+txtKit.getText()+
                "\nLote"+txtLote.getText()+
                "\nEnfermedad: "+txtEnfermedad.getText()+
                "\nDosis: "+txtDosis.getText()+
                "\nCaduca: "+txtCaduca.getText());
            FormVacunarPaciente.showJPanel(new ConfirmarVacuna(this.pacienteVacunado()));
        }else{
            JOptionPane.showMessageDialog(null, "Seleccione una vacuna.");
        }
        
    }//GEN-LAST:event_btnSeleccionarVacunaActionPerformed

    private void txtLoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLoteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLoteActionPerformed

    private void txtDosisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDosisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDosisActionPerformed

    private void txtCaducaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCaducaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCaducaActionPerformed

    private void tbTotalVacunasDisponiblesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbTotalVacunasDisponiblesMouseClicked
        // TODO add your handling code here:
        ConexionVacunasDisponibles objetoVacDIs=new ConexionVacunasDisponibles();
        objetoVacDIs.seleccionarVacunaDisponible(tbTotalVacunasDisponibles, txtKit, txtLote, txtEnfermedad, txtDosis, txtCaduca);
    }//GEN-LAST:event_tbTotalVacunasDisponiblesMouseClicked

    private void txtFechaNacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaNacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaNacActionPerformed

    private void txtCelularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCelularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCelularActionPerformed

    private void txtDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDireccionActionPerformed

    private void txtDniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDniActionPerformed

    private void txtBuscarKitOLoteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKitOLoteKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarKitOLoteKeyTyped

    private void txtBuscarKitOLoteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKitOLoteKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtBuscarKitOLoteKeyPressed

    private void txtBuscarKitOLoteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKitOLoteKeyReleased
        // TODO add your handling code here:
        if(cbTipoDeBusqueda.getSelectedItem().toString().equals("buscar por kit")){
            ConexionVacunasDisponibles buscarPorKit=new ConexionVacunasDisponibles();
            buscarPorKit.filtrarVacunaPorKitOLote(tbTotalVacunasDisponibles, txtBuscarKitOLote, 0);
        }
        if (cbTipoDeBusqueda.getSelectedItem().toString().equals("buscar por lote")) {
            ConexionVacunasDisponibles buscarPorLote=new ConexionVacunasDisponibles();
            buscarPorLote.filtrarVacunaPorKitOLote(tbTotalVacunasDisponibles, txtBuscarKitOLote, 1);
        }
    }//GEN-LAST:event_txtBuscarKitOLoteKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JButton btnSeleccionarVacuna;
    private javax.swing.JComboBox<String> cbTipoDeBusqueda;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel lblBienvenido;
    private javax.swing.JTable tbTotalVacunasDisponibles;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtBuscarKitOLote;
    private javax.swing.JTextField txtCaduca;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtDni;
    private javax.swing.JTextField txtDosis;
    private javax.swing.JTextField txtEnfermedad;
    private javax.swing.JTextField txtFechaNac;
    private javax.swing.JTextField txtKit;
    private javax.swing.JTextField txtLote;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
